### ISSUE TITLE
Question: set MasterView programmatically independently of DetailView

### ISSUE THREAD

**Issue by CuriousDev21** [twodayslate/SplitTabBar#1]
Hello,

Thank you for the cool effort in making this project.

I wanted to test it out for my use case where I have an app which uses a Tabbarcontroller behind a navigation controller as root view. 

I want to have one specific view controller as master and the tabbarcontroller as detail (They do not sync between each other).

Could you advise on how to achieve?

Thank you.

**Comment by twodayslate** [comment]
> A split view controller must always be the root of any interface you create. 

-- [Split View Controllers](https://developer.apple.com/library/archive/documentation/WindowsViews/Conceptual/ViewControllerCatalog/Chapters/SplitViewControllers.html#//apple_ref/doc/uid/TP40011313-CH7)

If you are able to find a workaround please let me know (I'm sure it is possible).

If you want to just change the master and detail view controllers of `SplitTabBarViewController` you can do that in the [initialization function](https://github.com/twodayslate/SplitTabBar/blob/master/Sources/SplitTabBar/SplitTabBarViewController.swift#L19-L22). Subclassing and overriding will be required.
